Algoritmo "Creuza04"

// Disciplina  : Algoritmos
// Professor   : Gustavo Guanabara
// Descrição   : Aula 6 – Exercícios de Algoritmo Resolvidos
// Autor(a)    : Wady Jorge
// Ano         : 2024

Var

	// Variáveis
	preco, imposto: real
   
Inicio

	Escreval ("Qual é o preço do produto? ")
	Leia (preco)
   imposto <- (preco * 60) / 100
	Escreval ("O imposto será de US$:", imposto)
   
Fimalgoritmo