Algoritmo "Creuza01"

// Disciplina  : Algoritmos
// Professor   : Gustavo Guanabara
// Descrição   : Aula 6 – Exercícios de Algoritmo Resolvidos
// Autor(a)    : Wady Jorge
// Ano         : 2024

Var

	// Variáveis
	ano_atual, ano_nasc, idade: inteiro
   
Inicio

	Escreval ("Em que ano nós estamos? ")
	Leia (ano_atual)
	Escreval ("Em que ano eu nasci? ")
	Leia (ano_nasc)
	idade <- ano_atual - ano_nasc
	Escreval ("Minha idade é:", idade)
   
Fimalgoritmo