Algoritmo "Contador"

// Disciplina  : Algoritmos
// Professor   : Gustavo Guanabara
// Descrição   : Aula 11 – Estruturas de Repetição 3
// Autor(a)    : Wady Jorge
// Ano         : 2024

Var

   // Variáveis
   contador: inteiro

Inicio

   // Funções
   Escreval("Olá! Sou um contador! Conto até 10!")
   
   Para contador <- 1 ate 10 faca
      Escreval(contador)
   FimPara
   Escreval("Terminei de contar!")

Fimalgoritmo