Algoritmo "ValoresPares"

// Disciplina  : Algoritmos
// Professor   : Gustavo Guanabara
// Descrição   : Aula 11 – Estruturas de Repetição 3
// Autor(a)    : Wady Jorge
// Ano         : 2024

Var

   // Variáveis
   contador, numero: inteiro

Inicio

   Escreval("Digite um valor para ver todos os números pares antes dele: ")
   Leia(numero)
   
   Para contador <- 0 ate numero passo 2 faca
      Escreva(contador, "...")
   FimPara

Fimalgoritmo