Algoritmo "ParOuImpar"

// Disciplina  : Algoritmos
// Professor   : Gustavo Guanabara
// Descrição   : Aula 7 – Estruturas Condicionais 1
// Autor(a)    : Wady Jorge
// Ano         : 2024

Var

   // Variáveis
   numero : inteiro

Inicio

   // Funções
   Escreval ("Digite um número qualquer: ")
   Leia (numero)

   Se (numero % 2 = 0) entao
      Escreval ("O número", numero, " é PAR!")
   Senao
      Escreval ("O número", numero, " é IMPAR!")
   FimSe

Fimalgoritmo