Algoritmo "Contador01"

// Disciplina  : Algoritmos
// Professor   : Gustavo Guanabara
// Descrição   : Aula 9 – Estruturas de Repetição 1
// Autor(a)    : Wady Jorge
// Ano         : 2024

Var

   // Variáveis
   contador: inteiro

Inicio

   // Funções
   Escreval("Olá! Sou um contador! Conto até 10!")
   contador <- 0
   Enquanto (contador <= 10) faca
      Escreval(contador)
      contador <- contador + 1
   FimEnquanto
   Escreval("Terminei de contar!")

Fimalgoritmo